import json

filepath = 'Youtube-Truecrime-FLUX-Zai-KokoroTTS-T4.ipynb'
with open(filepath, 'r', encoding='utf-8') as f:
    text = f.read()

# The old Z Image function (find its boundaries in the JSON source array)
old_func = '''"def run_phase_1_z_image():\\n",
        "    import requests, time, urllib.request\\n",
        "    print(\\"\\\\n\\" + \\"=\\"*60)\\n",
        "    print(\\"PHASE 1: Image Generation (Z Image API)\\")\\n",
        "    print(\\"=\\"*60)\\n",
        "    \\n",
        "    if not Z_IMAGE_KEY:\\n",
        "        raise ValueError(\\"Z_IMAGE_KEY is missing but USE_Z_IMAGE is True.\\")\\n",
        "\\n",
        "    headers = {\\n",
        "        \\"Authorization\\": f\\"Bearer {Z_IMAGE_KEY}\\",\\n",
        "        \\"Content-Type\\": \\"application/json\\"\\n",
        "    }\\n",
        "    \\n",
        "    serials = [str(r[\\"Serial number\\"]) for _, r in df.iterrows()]\\n",
        "    if all_outputs_exist(IMAGES_DIR, serials, \\".png\\"):\\n",
        "        print(\\"--\u003e All images already on disk. Skipping Z Image generation.\\")\\n",
        "        return\\n",
        "\\n",
        "    for idx, row in tqdm(df.iterrows(), total=len(df), desc=\\"Rendering via Z Image\\"):\\n",
        "        sn = str(row[\\"Serial number\\"])\\n",
        "        img_path = os.path.join(IMAGES_DIR, f\\"{sn}.png\\")\\n",
        "        if os.path.exists(img_path):\\n",
        "            continue\\n",
        "\\n",
        "        prompt = str(row[\\"image prompt\\"])\\n",
        "        \\n",
        "        # 1. Create task\\n",
        "        create_payload = {\\n",
        "            \\"model\\": \\"z-image\\",\\n",
        "            \\"input\\": {\\n",
        "                \\"prompt\\": prompt,\\n",
        "                \\"aspect_ratio\\": ASPECT_RATIO,\\n",
        "                \\"nsfw_checker\\": False\\n",
        "            }\\n",
        "        }\\n",
        "        \\n",
        "        # Adding simple retry loop for API rate limits / generic errors\\n",
        "        max_retries = 3\\n",
        "        task_id = None\\n",
        "        for attempt in range(max_retries):\\n",
        "            try:\\n",
        "                resp = requests.post(\\"https://api.kie.ai/api/v1/jobs/createTask\\", json=create_payload, headers=headers)\\n",
        "                resp.raise_for_status()\\n",
        "                data = resp.json()\\n",
        "                if data.get(\\"code\\") == 200:\\n",
        "                    task_id = data.get(\\"data\\", {}).get(\\"taskId\\")\\n",
        "                    break\\n",
        "                else:\\n",
        "                    print(f\\"  [WARN] Attempt {attempt+1}: API Error: {data}\\")\\n",
        "            except Exception as e:\\n",
        "                print(f\\"  [WARN] Attempt {attempt+1}: Request failed: {e}\\")\\n",
        "            time.sleep(3)\\n",
        "            \\n",
        "        if not task_id:\\n",
        "            print(f\\"  [ERROR] Failed to create task for {sn}. Skipping.\\")\\n",
        "            continue\\n",
        "            \\n",
        "        # 2. Poll status\\n",
        "        success = False\\n",
        "        for _ in range(60): # Max 5 mins (60 * 5s)\\n",
        "            time.sleep(5)\\n",
        "            try:\\n",
        "                poll_resp = requests.get(f\\"https://api.kie.ai/api/v1/jobs/recordInfo?taskId={task_id}\\", headers=headers)\\n",
        "                poll_data = poll_resp.json()\\n",
        "                if poll_data.get(\\"code\\") == 200:\\n",
        "                    state = poll_data.get(\\"data\\", {}).get(\\"state\\")\\n",
        "                    if state == \\"success\\":\\n",
        "                        res_json = json.loads(poll_data.get(\\"data\\", {}).get(\\"resultJson\\", \\"{}\\"))\\n",
        "                        urls = res_json.get(\\"resultUrls\\", [])\\n",
        "                        if urls:\\n",
        "                            urllib.request.urlretrieve(urls[0], img_path)\\n",
        "                            print(f\\"  Saved {sn}.png\\")\\n",
        "                            success = True\\n",
        "                        break\\n",
        "                    elif state == \\"fail\\":\\n",
        "                        print(f\\"  [ERROR] Task failed for {sn}: {poll_data.get('data', {}).get('failMsg')}\\")\\n",
        "                        break\\n",
        "            except Exception as e:\\n",
        "                pass\\n",
        "                \\n",
        "        if not success:\\n",
        "            print(f\\"  [ERROR] Could not fetch image for {sn}.\\")\\n",
        "\\n",
        "    # Zip output\\n",
        "    zip_path = os.path.join(OUTPUTS_DIR if 'OUTPUTS_DIR' in globals() else OUTPUT_DIR, \\"source_images.zip\\")\\n",
        "    with zipfile.ZipFile(zip_path, \\"w\\") as z:\\n",
        "        for f in os.listdir(IMAGES_DIR):\\n",
        "            z.write(os.path.join(IMAGES_DIR, f), arcname=f)\\n",
        "    print(\\"--\u003e Phase 1 Z Image complete.\\")\\n",'''

new_func = '''"def run_phase_1_z_image():\\n",
        "    import requests, time, urllib.request\\n",
        "    print(\\"\\\\n\\" + \\"=\\"*60)\\n",
        "    print(\\"PHASE 1: Image Generation (Z Image API)\\")\\n",
        "    print(\\"=\\"*60)\\n",
        "    \\n",
        "    if not Z_IMAGE_KEY:\\n",
        "        raise ValueError(\\"Z_IMAGE_KEY is missing but USE_Z_IMAGE is True.\\")\\n",
        "    print(f\\"  API Key: {Z_IMAGE_KEY[:8]}...{Z_IMAGE_KEY[-4:]}\\")\\n",
        "\\n",
        "    headers = {\\n",
        "        \\"Authorization\\": f\\"Bearer {Z_IMAGE_KEY}\\",\\n",
        "        \\"Content-Type\\": \\"application/json\\"\\n",
        "    }\\n",
        "    \\n",
        "    serials = [str(r[\\"Serial number\\"]) for _, r in df.iterrows()]\\n",
        "    if all_outputs_exist(IMAGES_DIR, serials, \\".png\\"):\\n",
        "        print(\\"--\u003e All images already on disk. Skipping Z Image generation.\\")\\n",
        "        return\\n",
        "\\n",
        "    for idx, row in tqdm(df.iterrows(), total=len(df), desc=\\"Rendering via Z Image\\"):\\n",
        "        sn = str(row[\\"Serial number\\"])\\n",
        "        img_path = os.path.join(IMAGES_DIR, f\\"{sn}.png\\")\\n",
        "        if os.path.exists(img_path):\\n",
        "            continue\\n",
        "\\n",
        "        prompt = str(row[\\"image prompt\\"])[:120]\\n",
        "        print(f\\"\\\\n  [{sn}] Prompt: {prompt}...\\")\\n",
        "        \\n",
        "        # 1. Create task\\n",
        "        create_payload = {\\n",
        "            \\"model\\": \\"z-image\\",\\n",
        "            \\"input\\": {\\n",
        "                \\"prompt\\": str(row[\\"image prompt\\"]),\\n",
        "                \\"aspect_ratio\\": ASPECT_RATIO,\\n",
        "                \\"nsfw_checker\\": False\\n",
        "            }\\n",
        "        }\\n",
        "        print(f\\"  Sending createTask to kie.ai...\\")\\n",
        "        \\n",
        "        max_retries = 3\\n",
        "        task_id = None\\n",
        "        for attempt in range(max_retries):\\n",
        "            try:\\n",
        "                resp = requests.post(\\"https://api.kie.ai/api/v1/jobs/createTask\\", json=create_payload, headers=headers, timeout=30)\\n",
        "                print(f\\"  Response status: {resp.status_code}\\")\\n",
        "                print(f\\"  Response body: {resp.text[:500]}\\")\\n",
        "                resp.raise_for_status()\\n",
        "                data = resp.json()\\n",
        "                if data.get(\\"code\\") == 200:\\n",
        "                    task_id = data.get(\\"data\\", {}).get(\\"taskId\\")\\n",
        "                    print(f\\"  Task created: {task_id}\\")\\n",
        "                    break\\n",
        "                else:\\n",
        "                    print(f\\"  [WARN] Attempt {attempt+1}: API returned code {data.get('code')}: {data}\\")\\n",
        "            except Exception as e:\\n",
        "                print(f\\"  [WARN] Attempt {attempt+1}: Request failed: {type(e).__name__}: {e}\\")\\n",
        "            time.sleep(3)\\n",
        "            \\n",
        "        if not task_id:\\n",
        "            print(f\\"  [ERROR] Failed to create task for {sn}. Skipping.\\")\\n",
        "            continue\\n",
        "            \\n",
        "        # 2. Poll status\\n",
        "        print(f\\"  Polling for result (max 5 min)...\\")\\n",
        "        success = False\\n",
        "        for poll_num in range(60):\\n",
        "            time.sleep(5)\\n",
        "            try:\\n",
        "                poll_resp = requests.get(f\\"https://api.kie.ai/api/v1/jobs/recordInfo?taskId={task_id}\\", headers=headers, timeout=15)\\n",
        "                poll_data = poll_resp.json()\\n",
        "                state = poll_data.get(\\"data\\", {}).get(\\"state\\", \\"unknown\\")\\n",
        "                if poll_num % 6 == 0:\\n",
        "                    print(f\\"    Poll #{poll_num+1}: state={state}\\")\\n",
        "                if poll_data.get(\\"code\\") == 200:\\n",
        "                    if state == \\"success\\":\\n",
        "                        res_json = json.loads(poll_data.get(\\"data\\", {}).get(\\"resultJson\\", \\"{}\\"))\\n",
        "                        urls = res_json.get(\\"resultUrls\\", [])\\n",
        "                        if urls:\\n",
        "                            urllib.request.urlretrieve(urls[0], img_path)\\n",
        "                            print(f\\"  Saved {sn}.png\\")\\n",
        "                            success = True\\n",
        "                        else:\\n",
        "                            print(f\\"  [ERROR] Success but no URLs: {res_json}\\")\\n",
        "                        break\\n",
        "                    elif state == \\"fail\\":\\n",
        "                        print(f\\"  [ERROR] Task failed for {sn}: {poll_data.get('data', {}).get('failMsg')}\\")\\n",
        "                        break\\n",
        "                else:\\n",
        "                    print(f\\"  [WARN] Poll returned code {poll_data.get('code')}: {poll_data}\\")\\n",
        "            except Exception as e:\\n",
        "                print(f\\"  [WARN] Poll error: {type(e).__name__}: {e}\\")\\n",
        "                \\n",
        "        if not success:\\n",
        "            print(f\\"  [ERROR] Could not fetch image for {sn} after {poll_num+1} polls.\\")\\n",
        "\\n",
        "    # Zip output\\n",
        "    zip_path = os.path.join(OUTPUT_DIR, \\"source_images.zip\\")\\n",
        "    with zipfile.ZipFile(zip_path, \\"w\\") as z:\\n",
        "        for f_name in os.listdir(IMAGES_DIR):\\n",
        "            z.write(os.path.join(IMAGES_DIR, f_name), arcname=f_name)\\n",
        "    print(\\"--\u003e Phase 1 Z Image complete.\\")\\n",'''

if old_func in text:
    text = text.replace(old_func, new_func)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(text)
    print("SUCCESS: Z Image function replaced with debug version.")
else:
    print("ERROR: Could not find the old Z Image function in notebook.")
    # Let's try to find what's there
    if 'run_phase_1_z_image' in text:
        print("  The function name exists but the exact text didn't match.")
        # Find the line numbers
        lines = text.split('\n')
        for i, line in enumerate(lines):
            if 'run_phase_1_z_image' in line:
                print(f"  Line {i+1}: {line[:100]}")
    else:
        print("  The function doesn't exist at all in the notebook!")
